default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: translator_rails_app_development

test:
  <<: *default
  database: translator_rails_app_test

production:
  <<: *default
  database: translator_rails_app_production
  username:
  password: